### ISSUE TITLE
Trouble getting consistent readings.

### ISSUE THREAD

**Issue by psyciknz** [klaasnicolaas/home-assistant-glow#162]
I get the occasional spikes, or nothing over night.  And seems to find when adjusting the photodiode a real small window towards the clockwise side where it will pick up values....

And normally it takes adjusting a fraction to the left and right of this point.   Then I'll see the logs start working, only for it to top later on.

I've tried setting the internal_filter_mode on recommendation of a thread, to no effect.

Any ideas where I can go from here?  As far as I can tell, I'm using a milk bottle lid with the photodiode inside, and it fairly well taped up.   On the thought that there was light bleeding in.  I've also put black tape over teh red and green leds on the photodiode in the hope that when it stopped at night, it was because on this light bleed.

https://cdn.discordapp.com/attachments/754605569003749426/966462065499844679/IMG_8159.jpg

BTW the screw is just through the hole of the photodiode, and is taped both sides as well, so shoudln't be shorting anywhere.

**Comment by newhinton** [comment]
I have the same weird issue. It seems that at night when the power drops below a certain threshhold, glow does not calculate the value properly.

![image](https://github.com/klaasnicolaas/home-assistant-glow/assets/25279821/3322e2bf-84f3-4ad0-8160-5c72ee290afc)

I assume the peaks are my fridge kicking on, but between those spikes, there should be at least a 30W measurement, because that is what my home-assistant server consumes. I would expect at least a permanent 40W measurement.
