### ISSUE TITLE
Reported Power Usage is higher in the day when I am generating solar but is accurate at night when i am not generating solar

### ISSUE THREAD

**Issue by andrewb2102** [klaasnicolaas/home-assistant-glow#274]
When I am generating solar, the power consumption value is reporting the power I am sending back to the grid, not the amount of power I am using. I figured this out by turning on my kettle and the power consumption dropped by 2000w. 

How do I fix this?

**Comment by Florian-Schmidt** [comment]
> If you know how much your solar production is, you might be able to make something with a template sensor 🤷‍♂️

Correct, I've got the same situation now and I know the production by the panels but I don't know the consumption of the producted energy. 
So I'm actually testing some template sensors to see if this could be a solution or minimum a workaround.

**Comment by larseggert** [comment]
Same issue here - power meter seems to flash the LED also when I am selling power to the grid, which is a bit unexpected. Any ideas for a solution, other than going to something like https://github.com/jomjol/AI-on-the-edge-device?

**Comment by ahmadyusuf** [comment]
Try using the left calculation method for the daily power sensor instead of the default, that fixed the issue for me

  # Total day useage
  - platform: total_daily_energy
    name: '${friendly_name} - Daily Energy'
    id: sensor_total_daily_energy
    power_id: sensor_energy_pulse_meter
    unit_of_measurement: 'kWh'
    icon: mdi:circle-slice-3
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    **method: left**
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

**Comment by larseggert** [comment]
Thanks, am trying this now. Where is this documented & what does it to?

**Comment by Florian-Schmidt** [comment]
ESP documentation: https://esphome.io/components/sensor/total_daily_energy.html

I try to describe details:
https://community.home-assistant.io/t/esphome-total-daily-energy-sensor-rainfall/339214

**Comment by ahmadyusuf** [comment]
It got pointed out to me by someone on the Home Assistant group.

Check out this post
https://community.home-assistant.io/t/riemann-integral-calculates-wrong-values-with-electrical-devices/328174?fbclid=IwAR2w3XyfJh3A3stKCS_wK0cuag5sGcsSZS_xO4t2xZWVfxrVngMc1vB0LX0


The default method fails with systems having solar because the sensor doesn't report anything consumption for sometime and then we it starts reporting, you see a sudden spike in the daily usage because the default calculation method assumes the usage increased gradually from 0 to the current reading over the period of time it was not reporting everything.

Hope it makes sense

**Comment by larseggert** [comment]
This doesn't work for me, since the LED on my meter seems to blink both when drawing power rpm the grid and when generating power I to the grid. Anything else I could try? This is my lower meter, FWIW: https://www.echelon.com/assets/bltc1e4347bb1a04c1c/Smart-Meter-MTR-3000-IEC-Poly-Phase-datasheet.pdf

**Comment by Florian-Schmidt** [comment]
Changed my ESP configuration yesterday, first check today seems to be working. I’ll monitor it next days.

My alternative before has been a template sensor to calculate the real energy consumption by subtract the estimate self usage with a fixed value. This way wouldn‘t be reliable.

**Comment by Florian-Schmidt** [comment]
For me this solutions seems to work. The values are quite near to the reality just a little difference. 

In my case I extended to ESP configuration to have one more sensor with "left" method to be able to compare the behavior and calculate the sold energy. Meanwhile Home Assistant provides many helper function but I didn't find out if there's an easier way to do it.
