### ISSUE TITLE
Question about photodiode sensitivity

### ISSUE THREAD

**Issue by alemuro** [klaasnicolaas/home-assistant-glow#32]
Hello all, 

First of all, let me congratule you for this project! 🎉  

It's been a long time since I wanted to start playing with some ESP32 devices, and this has been enough to buy one 😋  I received my ESP32 a couple of days ago and I've been doing some testing since today.  

The reason I'm opening this issue is because I would like to ask if there is  some way to  change the sensitivity of the photodiode sensor. In spain  we have some sort of methacrylate protecting our  meters, this means there is a gap between the meter light and the photodiode. As far as I could check, this gap is preventing my sensor to properly read data. I manged to emulate this by using my smartphone. I realised it only worked fine when the sensor was stucked to the camera led... but it fails when there is a gap bigger to 1 cm. 

So, do you know if there is any chance to change this sensitivity?

Thanks in advance! :)

**Comment by nigotiator** [comment]
In Finland we have the same kind of protection but for me it seem to work though. I've compared the total power consumption per day between HA and Energy company and the gap is 1 KWh at the best.
For me the best way to read the sensor was to set it up like this https://ibb.co/R2Hm9v1 so the photodiode is pointing to the energy meter's led... Yeah, I need to print the case :D
Sensor I'm using is this https://www.aliexpress.com/item/32852231949.html

But I  have other issue. The meter has also kvarh (?) led which I guess casues some issues with the reading since I get values like this (4th line) every now and then... kvarh led doesn't blink that often
`
[13:37:25][D][sensor:131]: 'Mittari - Total energy': Sending state 126.89900 kWh with 3 decimals of accuracy
[13:37:26][D][sensor:131]: 'Mittari - Power consumption': Sending state 2926.82910 W with 0 decimals of accuracy
[13:37:26][D][sensor:131]: 'Mittari - Total energy': Sending state 126.90100 kWh with 3 decimals of accuracy
[13:37:26][D][sensor:131]: 'Mittari - Power consumption': Sending state 128571.42969 W with 0 decimals of accuracy
[13:37:28][D][sensor:131]: 'Mittari - Power consumption': Sending state 2880.00000 W with 0 decimals of accuracy
`
Just wondering if there is some way to filter those huge values out...

**Comment by slovdahl** [comment]
@nigotiator try adding e.g. `internal_filter: 30ms`. I had similar issues and tinkering with `internal_filter` solved it for me (https://esphome.io/components/sensor/pulse_meter.html#configuration-variables).

**Comment by nigotiator** [comment]
> @nigotiator try adding e.g. `internal_filter: 30ms`. I had similar issues and tinkering with `internal_filter` solved it for me (https://esphome.io/components/sensor/pulse_meter.html#configuration-variables).

Thanks for the tip! Currently I have 5ms there so let's try with that!

**Comment by nigotiator** [comment]
Yay, looks way better now! Thanks @slovdahl 
![Screenshot_20210912-235807](https://user-images.githubusercontent.com/477138/133002642-b9f576f3-411b-4cbb-8c1b-55f5b49ab7f3.jpg)

**Comment by slovdahl** [comment]
Great!

FWIW, I googled the technical specs of my meter and it said that the LED pulse is 30 ms +- 3 ms long. So technically something like 15 ms should be enough, but not until I changed it from 27 to 30 ms I got rid of all the spurious readings.

**Comment by klaasnicolaas** [comment]
Can we close this issue?

**Comment by alemuro** [comment]
Sure! All of theses has helped me a lot! Thanks guys 😄 
And also I managed to change the sensitivity of the sensor with a screwdriver 😋
