### ISSUE TITLE
Where to find pulse_meter.yaml

### ISSUE THREAD

**Issue by atanas1054** [klaasnicolaas/home-assistant-glow#384]
Hello,

Where can I find the pulse_meter.yaml file? I flashed an ESP32 with home assistant glow and connected through home assistant. I also have the ESPHome dashboard but can only edit the home-assistant-glow-76fb7c.yaml file

**Comment by klaasnicolaas** [comment]
This is located in the components folder. By default, ESPHome will only create a basic config when you add the Glow to your own ESPHome dashboard and all package imports are not included (but included during firmware building).

I'm considering adjusting the settings slightly so that the entire config is imported.

./Klaas
